__author__ = 'Clay H'
#Reads from golf.txt to display names and scores generated by golfwrite.py
def main():
    print("Here are the names and scores of our players:")
    record = get_record()
    print(record)



def get_record():
    infile = open('golf.txt', 'r')
    s_input = infile.read()
    return s_input
main()